class AddColumnsToCustomers < ActiveRecord::Migration[7.1]
  def change
    add_column :customers, :usuario, :string
    add_column :customers, :nombre, :string
    add_column :customers, :email, :string
    add_column :customers, :cedula, :string
    add_column :customers, :direccion, :string
    add_column :customers, :localidad, :string
    add_column :customers, :ciudad, :string
    add_column :customers, :telefono, :string
    add_column :customers, :descuento, :string
    add_column :customers, :saldo, :float
    add_column :customers, :rfc, :string
    add_column :customers, :informacion_adicional, :string
    add_column :customers, :notificacion_sms, :string
    add_column :customers, :aviso_pantalla, :string
    add_column :customers, :notificaciones_push, :string
    add_column :customers, :auto_activar_servicio, :string
    add_column :customers, :firewall, :string
    add_column :customers, :servicio, :string
    add_column :customers, :password_servicio, :string
    add_column :customers, :server_hotspot, :string
    add_column :customers, :ip, :string
    add_column :customers, :ip_local, :string
    add_column :customers, :estado, :string
    add_column :customers, :modelo_antena, :string
    add_column :customers, :password_cpe, :string
    add_column :customers, :mac_cpe, :string
    add_column :customers, :interfaz_lan, :string
    add_column :customers, :modelo_router_wifi, :string
    add_column :customers, :ip_router_wifi, :string
    add_column :customers, :mac_router_wifi, :string
    add_column :customers, :usuario_router_wifi, :string
    add_column :customers, :password_router_wifi, :string
    add_column :customers, :ssid_router_wifi, :string
    add_column :customers, :password_ssid_router_wifi, :string
    add_column :customers, :comentarios, :string
    add_column :customers, :coordenadas, :string
    add_column :customers, :costo_instalacion, :float
    add_column :customers, :precio_plan, :float
    add_column :customers, :forma_contratacion, :string
    add_column :customers, :sn_onu, :string
    add_column :customers, :estado_facturas, :string
    add_column :customers, :fecha_instalacion, :datetime
    add_column :customers, :fecha_cancelacion, :datetime
    add_column :customers, :fecha_corte, :datetime
    add_column :customers, :ultimo_cambio, :string
    add_column :customers, :plan_internet, :string
    add_column :customers, :zona, :string
    add_column :customers, :router, :string
    add_column :customers, :sectorial, :string
    add_column :customers, :tecnico, :string
    add_column :customers, :string, :string
    add_column :customers, :servicio_id, :string
    add_column :customers, :usuario_cpe, :string
    add_column :customers, :protocolo_conexion_cpe, :string
    add_column :customers, :facturas_pagadas, :string
    add_column :customers, :fecha_registro, :datetime
    add_column :customers, :asesor, :string
  end
end
